import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar  from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="bg-white text-gray-900 font-sans">
        {/* <nav className="bg-rose-100 text-rose-800 px-6 py-4 shadow-md">
          <ul className="flex space-x-6 font-semibold">
            <li>
              <Link href="/">Accueil</Link>
            </li>
            <li>
              <Link href="/vins">Nos Vins</Link>
            </li>
            <li>
              <Link href="/cavistes">Cavistes</Link>
            </li>
          </ul>
        </nav> */}
        <Navbar /> {/* ⬅️ Utilisation du composant */}
        <main>{children}</main>
      </body>
    </html>
  );
}
